-- Supabase schema for Kahoot party quiz

create table if not exists parties (
  id bigint generated by default as identity primary key,
  join_code text not null unique,
  status text not null default 'lobby',
  questions jsonb not null,
  current_question int not null default 0,
  question_started_at timestamptz,
  review_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists players (
  id bigint generated by default as identity primary key,
  party_id bigint not null references parties(id) on delete cascade,
  name text not null,
  score int not null default 0,
  joined_at timestamptz not null default now()
);

create table if not exists answers (
  id bigint generated by default as identity primary key,
  party_id bigint not null references parties(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  question_index int not null,
  choice_index int not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now(),
  unique (party_id, player_id, question_index)
);

create or replace function set_timestamp()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'parties_update_timestamp'
  ) then
    create trigger parties_update_timestamp
    before update on parties
    for each row
    execute function set_timestamp();
  end if;
end;
$$;

alter table parties
  add column if not exists question_started_at timestamptz,
  add column if not exists review_started_at timestamptz;
